load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:py_test.bzl", "py_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

filegroup(
    name = "test_sources",
    testonly = True,
    srcs = glob(["*_test.py"]),
    visibility = ["//define/testdata:__pkg__"],
)

py_test(
    name = "action_definition_test",
    size = "small",
    srcs = ["action_definition_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:diagnostics",
        "//define/compiler:parser",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "blocks_test",
    size = "small",
    srcs = ["blocks_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "comments_test",
    size = "small",
    srcs = ["comments_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "constructor_condition_test",
    size = "small",
    srcs = ["constructor_condition_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "destroy_particle_test",
    size = "small",
    srcs = ["destroy_particle_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
    ],
)

py_test(
    name = "destructor_condition_test",
    size = "small",
    srcs = ["destructor_condition_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_library(
    name = "conftest",
    srcs = ["conftest.py"],
    deps = [
        "//define/compiler:parser",
        "//define/compiler/lark:lark_standalone",
        "@pypi//pytest",
    ],
)

py_test(
    name = "error_messages_test",
    size = "small",
    srcs = ["error_messages_test.py"],
    deps = [
        ":conftest",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "extra_whitespace_test",
    size = "small",
    srcs = ["extra_whitespace_test.py"],
    deps = [
        ":conftest",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "file_encoding_test",
    size = "small",
    srcs = ["file_encoding_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "incomplete_statements_test",
    size = "small",
    srcs = ["incomplete_statements_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "local_name_format_test",
    size = "small",
    srcs = ["local_name_format_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "move_particle_test",
    size = "small",
    srcs = ["move_particle_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
    ],
)

py_test(
    name = "multiple_definitions_test",
    size = "small",
    srcs = ["multiple_definitions_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
    ],
)

py_library(
    name = "parser_tests",
    srcs = ["__init__.py"],
)

py_test(
    name = "position_definition_test",
    size = "small",
    srcs = ["position_definition_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "quality_implication_test",
    size = "small",
    srcs = ["quality_implication_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "statement_terminators_test",
    size = "small",
    srcs = ["statement_terminators_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_library(
    name = "test_helpers",
    srcs = ["test_helpers.py"],
    deps = ["//define/compiler/lark:lark_standalone"],
)

py_test(
    name = "trigger_conditions_test",
    size = "small",
    srcs = ["trigger_conditions_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

py_test(
    name = "typed_name_references_test",
    size = "small",
    srcs = ["typed_name_references_test.py"],
    deps = [
        ":conftest",
        ":test_helpers",
        "//define/compiler:parser_exceptions",
        "@pypi//pytest",
    ],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

# --- Type-checking ---

pyright_test(
    name = "pyright_test",
    deps = [
        ":action_definition_test",
        ":blocks_test",
        ":comments_test",
        ":conftest",
        ":constructor_condition_test",
        ":destroy_particle_test",
        ":destructor_condition_test",
        ":error_messages_test",
        ":extra_whitespace_test",
        ":file_encoding_test",
        ":incomplete_statements_test",
        ":local_name_format_test",
        ":move_particle_test",
        ":multiple_definitions_test",
        ":parser_tests",
        ":position_definition_test",
        ":quality_implication_test",
        ":statement_terminators_test",
        ":test_helpers",
        ":trigger_conditions_test",
        ":typed_name_references_test",
    ],
)
