load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:py_test.bzl", "py_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

py_library(
    name = "scope_tracker",
    srcs = ["scope_tracker.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = ["//define/compiler:ast"],
)

py_test(
    name = "scope_tracker_test",
    size = "small",
    srcs = ["scope_tracker_test.py"],
    deps = [
        ":scope_tracker",
        "//define/compiler:ast",
        "@pypi//pytest",
    ],
)

py_library(
    name = "test_helpers",
    testonly = True,
    srcs = ["test_helpers.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":validation_result",
        "//define/compiler:diagnostics",
    ],
)

py_library(
    name = "stats",
    srcs = ["stats.py"],
    visibility = ["//define/compiler:__subpackages__"],
)

py_test(
    name = "stats_test",
    size = "small",
    srcs = ["stats_test.py"],
    deps = [
        ":stats",
    ],
)

py_library(
    name = "validation_result",
    srcs = ["validation_result.py"],
    visibility = [
        "//define/compiler:__pkg__",
        "//define/compiler:__subpackages__",
    ],
    deps = [
        ":stats",
        "//define/compiler:ast",
        "//define/compiler:diagnostics",
        "//define/compiler:exceptions",
        "//define/compiler/data_structures:define_path",
        "//define/compiler/data_structures:typed_name_dict",
        "//define/compiler/graphs:reference_graph",
        "//define/compiler/lark:lark_standalone",
    ],
)

py_test(
    name = "validation_result_test",
    size = "small",
    srcs = ["validation_result_test.py"],
    deps = [
        ":stats",
        ":validation_result",
        "//define/compiler:ast",
        "//define/compiler:test_helpers",
        "//define/compiler/data_structures:define_path",
        "//define/compiler/graphs:reference_graph",
    ],
)

py_library(
    name = "validator",
    srcs = ["__init__.py"],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

# --- Type-checking ---

pyright_test(
    name = "pyright_test",
    deps = [
        ":scope_tracker",
        ":scope_tracker_test",
        ":stats",
        ":stats_test",
        ":test_helpers",
        ":validation_result",
        ":validation_result_test",
        ":validator",
    ],
)
