%import common.LF -> NEWLINE

# Name Terminals

# Both GLOBAL_NAME_CONTENT and LOCAL_NAME_CONTENT have negative priority
# so that keyword string terminals (priority 0) always win over them. This
# creates much better parser error messages and error classification.
# Otherwise, the parser thinks that every invalid state matches one
# of these two terminals, greatly reducing the accuracy of parser error
# states.

GLOBAL_NAME_CONTENT.-1: /([^> \n]+:){0,3}\/[^>\n]+/
# We have to make LOCAL_NAME_CONTENT exclude : and / in order to
# successfully differentiate it in circumstances where both local
# and global names are accepted.
#
# We also exclude space because it produces clearer error messages
# most of the time and I'm concerned about the code-generation security
# implications of allowing spaces in names (because the languages we
# transpile down to could do something unsafe with names with spaces in them).
LOCAL_NAME_CONTENT.-2: /[^:\/> \n]+/

# Syntax Terminals
DEFINE_THE_POSITION: "define the position"
DEFINE_THE_POTENTIAL_POSITION: "define the potential position"
DEFINE_THE_POTENTIAL_ACTION: "define the potential action"
NAME_TYPE: "position" | "action"
IT_MAY_ONLY_CONTAIN_PARTICLES_WHERE: "it may only contain particles where"
IT_HAS_THE: "it has the"
IT_HAPPENS_WHEN: "it happens when"
AND_IT_DOES: " and it does"
CREATE_A_PARTICLE_IN: "create a particle in "
MOVE_THE_PARTICLE_IN: "move the particle in "
DESTROY_THE_PARTICLE_IN: "destroy the particle in "
THE: "the "
HAS_A_PARTICLE: " has a particle"
CONSTRUCTOR_STATEMENT: "this particle is created"
DESTRUCTOR_STATEMENT: "this particle is being destroyed"
# TODO: Removing the spaces from this terminal and putting them in the grammar
# rules might produce better errors now that *_NAME_CONTENT terminals have
# negative priority.
TO: " to "
CHAIN_SEPARATOR: "::"
IT_ALSO_ASSIGNS_THE: "it also assigns the"

# General

# Ignore leading whitespace (indentation) on lines inside blocks.
# The lookbehind ensures we only match after a newline, and the
# lookahead ensures we don't consume trailing whitespace on blank lines.
%ignore /(?<=\n) +(?=\S)/

# Allow only visible characters in comments.
# TODO: Disallow invisible Unicode characters per spec.
COMMENT: / *#(?:[^\x00-\x1F\x7F]*[^\x00-\x1F\x7F ])?/
%ignore COMMENT

terminator: "." NEWLINE
SPACE_AND_OPEN_BRACE: " {"
CLOSE_BRACE: "}"
_block_open: SPACE_AND_OPEN_BRACE NEWLINE
_block_close: CLOSE_BRACE NEWLINE

# Name Syntax

global_name_definition_content: "<" GLOBAL_NAME_CONTENT ">"
global_name_reference_content: "<" GLOBAL_NAME_CONTENT ">"
local_name_content: "<" LOCAL_NAME_CONTENT ">"
typed_global_name_reference: NAME_TYPE global_name_reference_content
typed_local_name_reference: NAME_TYPE local_name_content
?typed_name_reference: typed_local_name_reference | typed_global_name_reference

# Position Constraint Block Syntax

position_requirement_statement: IT_HAS_THE " " typed_global_name_reference terminator
_position_constraint_requirements: NEWLINE* (position_requirement_statement NEWLINE*)+
position_constraint_block: IT_MAY_ONLY_CONTAIN_PARTICLES_WHERE _block_open _position_constraint_requirements _block_close

# Quality Implication Statement Syntax

quality_implication_statement: IT_ALSO_ASSIGNS_THE " " typed_global_name_reference terminator
_quality_implications: (quality_implication_statement NEWLINE*)*

# Local Position Definition Syntax

local_position_definition_block: _block_open NEWLINE* position_constraint_block NEWLINE* _block_close
?position_definition_terminator_or_block: terminator | local_position_definition_block

# Potential Position Definition Syntax

_action_statements: (NEWLINE | local_position_definition | create_particle_statement | move_particle_statement | destroy_particle_statement)*
potential_position_definition_block: _block_open NEWLINE* _quality_implications position_constraint_block NEWLINE* _block_close
position_definition: DEFINE_THE_POTENTIAL_POSITION global_name_definition_content (terminator | potential_position_definition_block)

# Particle Statement Syntax

position_reference: typed_name_reference (CHAIN_SEPARATOR typed_name_reference)*
create_particle_statement: CREATE_A_PARTICLE_IN position_reference terminator
move_particle_statement: MOVE_THE_PARTICLE_IN position_reference TO position_reference terminator
destroy_particle_statement: DESTROY_THE_PARTICLE_IN position_reference terminator

# Action Definition Syntax

action_definition: DEFINE_THE_POTENTIAL_ACTION global_name_definition_content action_definition_block

local_position_definition: DEFINE_THE_POSITION local_name_content position_definition_terminator_or_block
position_presence_statement: THE typed_local_name_reference HAS_A_PARTICLE terminator
constructor_condition_statement: CONSTRUCTOR_STATEMENT terminator
destructor_condition_statement: DESTRUCTOR_STATEMENT terminator
?trigger_condition_statement: position_presence_statement | constructor_condition_statement | destructor_condition_statement
trigger_conditions_block: IT_HAPPENS_WHEN _block_open NEWLINE* trigger_condition_statement NEWLINE* CLOSE_BRACE
action_statements_block: AND_IT_DOES _block_open _action_statements _block_close
_trigger_and_action: trigger_conditions_block action_statements_block
_action_local_position_definitions: (local_position_definition NEWLINE*)*
action_definition_block: _block_open NEWLINE* _quality_implications _action_local_position_definitions _trigger_and_action NEWLINE* _block_close

# Root Syntax

definition: position_definition | action_definition
start: NEWLINE* definition (NEWLINE* definition)* NEWLINE*
