load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "lark",
    srcs = ["__init__.py"],
    visibility = ["//define/compiler:__subpackages__"],
)

genrule(
    name = "lark_standalone_gen",
    srcs = ["//define/compiler:grammar.lark"],
    outs = ["lark_standalone.py"],
    cmd = "$(location //tools:generate_lark_standalone) $(location //define/compiler:grammar.lark) && mv lark_parser.py $@",
    tools = ["//tools:generate_lark_standalone"],
)

py_library(
    name = "lark_standalone",
    srcs = [":lark_standalone.py"],
    visibility = ["//define/compiler:__subpackages__"],
)
