load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:jinja2.bzl", "jinja_templates")
load("//tools/bzl:py_test.bzl", "py_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

py_library(
    name = "action_context",
    srcs = ["action_context.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        ":naming",
        ":template_context",
        "//define/compiler/codegen:action_plan",
        "//define/compiler/validator/reference_graph:operation_graph_model",
    ],
)

py_library(
    name = "action_definition",
    srcs = ["action_definition.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        ":action_context",
        ":action_execution",
        ":naming",
        ":template_context",
        "//define/compiler:ast",
        "//define/compiler/codegen:action_plan",
        "//define/compiler/data_structures:typed_name_dict",
        "//define/compiler/validator/reference_graph:operation_graph_labeler",
    ],
)

py_library(
    name = "action_execution",
    srcs = ["action_execution.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        ":action_context",
        ":action_guarantees",
        ":action_names",
        ":action_statements",
        ":naming",
        ":template_context",
        ":triggered_action_execution",
        "//define/compiler:ast",
        "//define/compiler/codegen:action_plan",
        "//define/compiler/data_structures:typed_name_dict",
        "//define/compiler/validator/reference_graph:operation_graph_labeler",
        "//define/compiler/validator/reference_graph:operation_graph_model",
    ],
)

py_library(
    name = "action_guarantees",
    srcs = ["action_guarantees.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        ":action_context",
        ":action_names",
        ":naming",
        ":template_context",
        "//define/compiler:ast",
        "//define/compiler/codegen:action_plan",
        "//define/compiler/data_structures:typed_name_dict",
        "//define/compiler/validator/reference_graph:operation_graph",
        "//define/compiler/validator/reference_graph:operation_graph_model",
    ],
)

py_library(
    name = "action_names",
    srcs = ["action_names.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        ":action_context",
        ":naming",
        "//define/compiler:ast",
        "//define/compiler/codegen:action_plan",
        "//define/compiler/data_structures:typed_name_dict",
        "//define/compiler/validator/reference_graph:operation_graph_action_resolver",
        "//define/compiler/validator/reference_graph:operation_graph_model",
        "//define/compiler/validator/reference_graph:position_occupancy",
    ],
)

py_test(
    name = "action_names_test",
    size = "small",
    srcs = ["action_names_test.py"],
    deps = [
        ":action_context",
        ":action_names",
        "//define/compiler:ast",
        "//define/compiler:conftest",
        "//define/compiler:test_helpers",
        "//define/compiler/codegen:action_plan",
        "//define/compiler/data_structures:typed_name_dict",
        "//define/compiler/validator:test_helpers",
        "//define/compiler/validator/reference_graph:operation_graph_action_resolver",
        "//define/compiler/validator/reference_graph:operation_graph_model",
        "//define/compiler/validator/reference_graph:position_occupancy",
    ],
)

py_library(
    name = "action_statements",
    srcs = ["action_statements.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        ":naming",
        ":template_context",
        "//define/compiler:ast",
        "//define/compiler/codegen:action_plan",
        "//define/compiler/validator/reference_graph:operation_graph_labeler",
        "//define/compiler/validator/reference_graph:operation_graph_model",
    ],
)

py_library(
    name = "generator",
    srcs = ["generator.py"],
    data = [":templates"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        ":action_context",
        ":action_definition",
        ":naming",
        ":position_definition",
        ":template_context",
        ":template_env",
        "//define/compiler:ast",
        "//define/compiler/codegen:action_plan",
        "//define/compiler/data_structures:typed_name_dict",
        "//define/compiler/graphs:reference_graph_executor",
        "//define/compiler/validator/reference_graph:operation_graph",
        "//define/compiler/validator/reference_graph:operation_graph_labeler",
        "@pypi//jinja2",
    ],
)

py_library(
    name = "naming",
    srcs = ["naming.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        "//define/compiler:ast",
        "//define/compiler:constants",
        "//define/compiler/data_structures:define_path",
    ],
)

py_test(
    name = "naming_test",
    size = "small",
    srcs = ["naming_test.py"],
    deps = [
        ":naming",
        "//define/compiler:ast",
        "//define/compiler/data_structures:define_path",
    ],
)

py_library(
    name = "position_definition",
    srcs = ["position_definition.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        ":naming",
        ":template_context",
        "//define/compiler:ast",
    ],
)

py_library(
    name = "python",
    srcs = ["__init__.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
)

py_library(
    name = "template_context",
    srcs = ["template_context.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        ":naming",
        "//define/compiler:ast",
        "//define/compiler/validator/reference_graph:operation_graph_labeler",
    ],
)

py_library(
    name = "template_env",
    srcs = ["template_env.py"],
    visibility = [
        "//define/compiler/codegen:__subpackages__",
        "//tools:__pkg__",
    ],
    deps = ["@pypi//jinja2"],
)

py_test(
    name = "template_env_test",
    size = "small",
    srcs = ["template_env_test.py"],
    data = [":templates"],
    deps = [":template_env"],
)

jinja_templates(
    name = "templates",
    srcs = glob(["*.j2"]),
)

py_library(
    name = "triggered_action_execution",
    srcs = ["triggered_action_execution.py"],
    visibility = ["//define/compiler/codegen:__subpackages__"],
    deps = [
        ":action_context",
        ":action_guarantees",
        ":action_names",
        ":action_statements",
        ":naming",
        ":template_context",
        "//define/compiler:ast",
        "//define/compiler/codegen:action_plan",
        "//define/compiler/data_structures:typed_name_dict",
        "//define/compiler/validator/reference_graph:operation_graph_labeler",
        "//define/compiler/validator/reference_graph:operation_graph_model",
    ],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

# --- Type-checking ---

# IMPORTANT: When adding a new py_library, py_binary, or py_test target to this
# package, you must also add it to the deps list below.
pyright_test(
    name = "pyright_test",
    deps = [
        ":action_context",
        ":action_definition",
        ":action_execution",
        ":action_guarantees",
        ":action_names",
        ":action_names_test",
        ":action_statements",
        ":generator",
        ":naming",
        ":naming_test",
        ":position_definition",
        ":python",
        ":template_context",
        ":template_env",
        ":template_env_test",
        ":triggered_action_execution",
    ],
)
