load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "algorithm",
    srcs = ["algorithm.py"],
    visibility = ["//operation_graph_optimization:__pkg__"],
    deps = [":graph"],
)

py_library(
    name = "graph",
    srcs = ["graph.py"],
    visibility = ["//operation_graph_optimization:__pkg__"],
)
