load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library", py_test = "py_pytest_test")

py_binary(
    name = "benchmark",
    srcs = ["benchmark.py"],
    deps = [":compiler", ":descriptions", "@pypi//click"],
)

py_library(
    name = "compiler",
    srcs = ["compiler.py"],
    deps = [
        ":descriptions",
        "//operation_graph_optimization:algorithm",
        "//operation_graph_optimization:vanish_workloads",
        "//operation_graph_optimization/complete:algorithm",
        "//operation_graph_optimization/complete:graph",
    ],
)

py_library(
    name = "descriptions",
    srcs = ["descriptions.py"],
)

py_test(
    name = "interface_test",
    size = "small",
    srcs = ["interface_test.py"],
    data = ["//:pyproject.toml"],
    deps = [
        ":compiler",
        ":descriptions",
        "//operation_graph_optimization/complete:algorithm",
        "@pypi//coverage",
        "@pypi//pytest",
    ],
)
