load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:py_test.bzl", "py_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

py_library(
    name = "data_structures",
    srcs = ["__init__.py"],
    visibility = ["//define/compiler:__subpackages__"],
)

py_library(
    name = "define_path",
    srcs = ["define_path.py"],
    visibility = ["//define/compiler:__subpackages__"],
)

py_test(
    name = "define_path_test",
    size = "small",
    srcs = ["define_path_test.py"],
    deps = [
        ":define_path",
        "@pypi//pytest",
    ],
)

py_library(
    name = "trie",
    srcs = ["trie.py"],
    visibility = ["//define/compiler:__subpackages__"],
)

py_test(
    name = "trie_test",
    size = "small",
    srcs = ["trie_test.py"],
    deps = [
        ":trie",
        "@pypi//pytest",
    ],
)

py_library(
    name = "typed_name_dict",
    srcs = ["typed_name_dict.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = ["//define/compiler:ast"],
)

py_test(
    name = "typed_name_dict_test",
    size = "small",
    srcs = ["typed_name_dict_test.py"],
    deps = [
        ":typed_name_dict",
        "//define/compiler:ast",
        "@pypi//pytest",
    ],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

# --- Type-checking ---

pyright_test(
    name = "pyright_test",
    deps = [
        ":data_structures",
        ":define_path",
        ":define_path_test",
        ":trie",
        ":trie_test",
        ":typed_name_dict",
        ":typed_name_dict_test",
    ],
)
